"""Repository contracts — one interface per schema area."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProfileRepository(Protocol):
    def read_profile(self) -> dict[str, Any]: ...
    def write_profile(self, data: dict[str, Any]) -> None: ...


@runtime_checkable
class ChatRepository(Protocol):
    def read_chat(self) -> dict[str, Any]: ...
    def write_chat(self, data: dict[str, Any]) -> None: ...


@runtime_checkable
class CalendarRepository(Protocol):
    def read_calendar_month(self, year_month: str) -> dict[str, Any]: ...
    def write_calendar_month(self, year_month: str, data: dict[str, Any]) -> None: ...
    def find_block_month(self, block_id: str) -> str | None: ...
    def find_block(self, block_id: str) -> dict[str, Any] | None: ...
    def calendar_index_rows(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class UserStoreRepository(ProfileRepository, ChatRepository, CalendarRepository, Protocol):
    """Full per-user persistence surface used by the agent."""

    @property
    def user_id(self) -> str: ...

    @property
    def storage_backend(self) -> str: ...

    def profile_exists(self) -> bool: ...
    def chat_exists(self) -> bool: ...
    def planner_storage_index(self) -> dict[str, Any]: ...
